name: Compile, Test And Deliver a Java File

on:
  push:
    paths:
      - 'java/**'
      
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
    - name: Compile
      working-directory: java
      run: javac *.java

  test:
    runs-on: ubuntu-latest
    needs: compile
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
    - name: Compile
      working-directory: java
      run: javac *.java
    - name: Running
      working-directory: java
      run: "java NachKaufabschluss | grep -c Produkte"
    
  deliver:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
    - name: Compiling
      working-directory: java
      run: javac *.java
    - name: Creating JAR file
      working-directory: java
      run: jar -cf cd-java.jar *.class
    - name: Transfer to staging area
      uses: marcodallasanta/ssh-scp-deploy@v1.2.0
      with:
        local: 'java/*.jar'
        host: ${{secrets.SERVER_NAME}}
        user: ${{secrets.SERVER_USERNAME}}
        password: ${{secrets.SERVER_PASSWORD}} 
